# Generated by Django 4.2.3 on 2023-07-13 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texte',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textes', to='nlp_app.patient'),
        ),
    ]
